language: r
sudo: required
dist: trusty
cache: packages

addons:
  apt:
    packages:
      - libudunits2-dev

notifications:
  email:
    recipients:
      - roger.bivand@nhh.no
    on_success: never # default: change
    on_failure: always # default: always
